### ISSUE TITLE
Schema Upgrade when prior dists of Zaius_Engage were installed.

### ISSUE THREAD

**Issue by cBrenDev** [ZaiusInc/zaius-magento-2#1]
zaius-magento-2/Setup/UpgradeSchema.php doesn't seem to recognize that an upgrade is necessary during the install process, perhaps thanks to -beta.1

**Comment by travish** [comment]
Script added in https://github.com/ZaiusInc/zaius-magento-2/commit/384fdd5f0248ee06b46878e9f2aa4ef61063a3fe

**Comment by cBrenDev** [comment]
Partially fixed in 1.0.0-beta.3 but we've uncovered an issue on M2.3; fix pending in develop.

**Comment by cBrenDev** [comment]
Fix has been merged.
