### ISSUE TITLE
cart_json should be stringified, not an actual javascript object

### ISSUE THREAD

**Issue by cBrenDev** [ZaiusInc/zaius-magento-2#2]
Zaius will silently ignore it in its current state, but we need it to be usable in liquid for dynamic email content - for that it needs to be a string we can store and later parse into its original value again.

**Comment by travish** [comment]
https://github.com/ZaiusInc/zaius-magento-2/commit/969055fa4ab897bfa9e91a4f2928540d62591bd0

**Comment by cBrenDev** [comment]
Merged into release 1.0.0-beta.2
