### ISSUE TITLE
Zaius Cart Parameters must have different field names

### ISSUE THREAD

**Issue by cBrenDev** [ZaiusInc/zaius-magento-2#3]
https://github.com/ZaiusInc/zaius-magento-2/blob/0a0dbc931f443a655bfdfe06859c75e29267e321/Observer/CartAddObserver.php#L79-80

Zaius does not allow custom fields to begin with "zaius_" as we reserve this namespace for our own use.

Suggestion:
migrate "zaius_cart" to "cart_param"
migrate "zaius_cart_url" to "cart_url"; should this be fully-incorporated with the cart_param as well? It looks like this gives the base URL for cart recovery in the current incarnation.

**Comment by travish** [comment]
Modified in https://github.com/ZaiusInc/zaius-magento-2/commit/d87ec4689fbc9c0315691f05f50a95697e7498bd

**Comment by cBrenDev** [comment]
LGTM. Sorry I missed the important bit in the modified file where the param is added to the recovery url ;)

**Comment by cBrenDev** [comment]
Fixes went live in 1.0.0-beta.3
